### ISSUE TITLE
Commands give errors

### ISSUE THREAD

**Issue by pgpetrov2001** [uplus/vim-clang-rename#1]
Error detected while processing function <SNR>20_clang_rename[2]..<SNR>20_clang_rename_offset:
line    3:
E117: Unknown function: clang_rename#offset

**Comment by uplus** [comment]
@pgpetrov2001 
Thank you for reporting and sorry for a late reply.
I did not reproduce this problem in my environment.

The target autooad function `clang_rename#offset` exists in source code, but it looks like it is not autoloadable in your environment.

I don't know what caused it, but if you have a plugin lazily loaded in the plugin manager, you may experience the same problem.

If you need support, please paste a minimal vimrc.
